project:
  type: book
  output-dir: _book

book:
  title: "Apuntes varios"
  author: "Jonatan Salazar"
  language: "es"
  date: "5/11/2025"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: static/images/cover.png
  page-footer:
    left: "Copyright 2025, Jonatan Salazar" 
    right: 
      - icon: github
        href: https://github.com/
    border: true
  sidebar:
    logo: static/images/cover.png
    collapse-level: 1

  chapters:
    - index.qmd
    - part: qmd/prompt_engineering/1_intro.qmd
      chapters:
        - qmd/prompt_engineering/zero_shot.qmd
        - qmd/prompt_engineering/few_shot.qmd
        - qmd/prompt_engineering/chain_of_thought.qmd
        - qmd/prompt_engineering/meta_prompting.qmd
        - qmd/prompt_engineering/prompt_chaining.qmd
    - part: qmd/python/1_intro_py.qmd
      chapters:
        - qmd/python/strings.qmd
        - qmd/python/int_float_bool.qmd
        - qmd/python/operadores.qmd
        - qmd/python/input_casting.qmd

format:
  html:
    toc: true
    toc-depth: 3
    mainfont: Roboto
    monofont: Fira Code
    theme:
      light: flatly
      dark: darkly
    css: styles/theme.css



